name: movie_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter_glow:
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_advanced_drawer: null
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  http: null
  lottie: null
  meta: ^1.10.0
  path: ^1.8.3
  youtube_player_flutter: ^9.0.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.3
 
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
